theme: jekyll-theme-minimal
title: Jonathan's homepage
description: Project/progress updates!

domain: modopo.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://modopo.github.io 